#!/usr/bin/env python

#
# Copyright 2015 Paul Donohue <cgroups_status@PaulSD.com>
#
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with this program.  If
# not, see <http://www.gnu.org/licenses/>.
#

#
# cgroups status checking tool for processes handled by etc/rails_handler.py
#
# See the comments in cgroups_status.py for prerequisites.
#

import cgroups_status

if __name__ == '__main__':
  cgroups_status.print_all_cgroups(subsystems=['memory'], sub_groups=['RoR'])
